"set changes only to vim and not vi?
"set nocompatible

"encoding"
"set encoding=utf-8

" Color schemes!
colorscheme monokai

"Line Numbers
set number

"Syntax highlighting
syntax on

" Wrap text
set wrap

" Auto Handle Indentation
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" This is similar?
set autoindent

" Good coding practice here
set textwidth=80

" New modes? Sure ok
func! WordProcessorMode()
 setlocal textwidth=80
 setlocal smartindent
 setlocal spell spelllang=en_us
 setlocal noexpandtab
endfu


" Set 7 lines to the cursor - when moving vertically using j/k
set so=7

" Turn on the Wild menu
set wildmenu

" Always show current position
set ruler

" Height of the command bar
set cmdheight=1

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" When searching try to be smart about cases
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch

" For regular expressions turn magic on
set magic

" Show matching brackets when text indicator is over them
set showmatch

" How many tenths of a second to blink when matching brackets
set mat=2

" No annoying sound on errors
set belloff=all
set noerrorbells
set novisualbell
set t_vb=
set tm=500
